DROP TABLE rates IF EXISTS;

CREATE TABLE rates (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_currency     VARCHAR(10),
  to_currency       VARCHAR(10),
  full_name         VARCHAR(255),
  date              DATE,
  timestamp         BIGINT,
  exchange_rate     DECFLOAT(6)
);
CREATE INDEX rates_from_to_currency ON rates (from_currency,to_currency);

